version: "3.9"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile

services:
  db:
    image: postgres:14.6-alpine
    env_file: .env
    ports:
      - "5432:5432"

  app:
    build: *dockerfile-dev-build
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./scripts/start-app.sh",
      ]
